canciones = {
    "Live Forever de Oasis": "Maybe I don't really wanna know How your garden grows 'Cause I just wanna fly Lately, did you ever feel the pain In the morning rain As it soaks you to the bone? Maybe I just wanna fly Wanna live, I don't wanna die Maybe I just wanna breathe Maybe I just don't believe Maybe you're the same as me We see things they'll never see You and I are gonna live forever I said maybe I don't really wanna know How your garden grows 'Cause I just wanna fly Lately, did you ever feel the pain In the morning rain As it soaks you to the bone? Maybe I will never be All the things that I wanna be Now is not the time to cry Now's the time to find out why I think you're the same as me We see things they'll never see You and I are gonna live forever Maybe I don't really wanna know How your garden grows 'Cause I just wanna fly Lately, did you ever feel the pain In the morning rain As it soaks you to the bone? Maybe I just wanna fly Wanna live, I don't wanna die Maybe I just wanna breathe Maybe I just don't believe Maybe you're the same as me We see things they'll never see You and I are gonna live forever Gonna live forever Gonna live forever We're gonna live forever We're gonna live forever We're gonna live forever We're gonna live forever",
    "Rhinestone Eyes by Gorillaz": "I'm a scary gargoyle on a tower That you made with plastic power Your rhinestone eyes are like factories far away When the paralytic dreams that we all seem to keep Drive on engines 'til they weep With future pixels in factories far away So call the mainland from the beach All parties now washed up in bleach The waves are rising for this time of year And nobody knows what to do with the heat Under sunshine pylons, we'll meet While rain is falling like rhinestones from the sky I got a feeling now my heart is frozen All the verses and the corrosion Have been after native in my soul I prayed on the unmovable Yeah, clinging to the atoms of rock Seasons, the adjustments Times have changed I can't see now, she said, Taxi Now that light is so I can take This storm brings strange loyalties and skies I'm a scary gargoyle on a tower That you made with plastic power Your rhinestone eyes are like factories far away Here we go again That's electric That's electric Helicopters fly over the beach Same time every day, same routine A clear target in the summer when skies are blue It's part of the noise when winter comes It reverberates in my lungs Nature's corrupted in factories far away Here we go again That's electric Your love's like rhinestones falling from the sky That's electric With future pixels in factories far away Here we go again That's electric Your love's like rhinestones falling from the sky That's electric With future pixels in factories far away Here we go again",
    "Pretty Old Man by No Buses": "Your breath blows my hair in this crowded space It stinks all the time because you're older You smoke every time You will be critically ill I wish you live longer and longer Work hard all day long You must take a rest Feeling want to cry Lost your honor Mom always read it to me and go to sleep early Need to remember over and over We can live forever We can live for-e-ver We just sleep forever Just sleep for-e-ver You can sleep forever Can sleep for-e-ver We just sleep forever-er Work hard all day long You must take a rest Feeling want to cry Lost your honor Mom always read it to me and go to sleep early Need to remember over and over We can live forever We can live for-e-ver We just sleep forever We just sleep for-e-ver You can sleep forever Can sleep for-e-ver We just sleep forever-er We can live forever We can live for-e-ver We just sleep forever We just sleep for-e-ver You can sleep forever Can sleep for-e-ver We just sleep forever-er",
}

print("Bienvenido, por favor, selecciona una canción de este top de 3 canciones:")
for i, cancion in enumerate(canciones, start=1):
    print(f"{i}. {cancion}")

seleccion = int(input())
if 1 <= seleccion <= len(canciones):
    cancion_seleccionada = list(canciones.keys())[seleccion - 1]
    letra = canciones[cancion_seleccionada]
    print(f"Has seleccionado '{cancion_seleccionada}'. Te mostramos la letra a continuación:\n")
    print("-------", cancion_seleccionada, "------------")
    print(letra)
else:
    print("Selección no válida.")